name: oxlint
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit --prod
      - run: pnpm fmt:check
      - run: pnpm lint
