name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm to latest
        run: |
          npm -v
          npm config set prefix ~/.local
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          npm install -g npm@latest np
          hash -r
          npm -v
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build
      - name: Verify publish artifacts
        run: npm pack
      - name: Verify package exports
        run: npx publint --pack npm
      - name: Check types compatibility
        run: npx attw --pack . --profile node16
      - name: Publish to NPM
        run: |
          npm -v
          ls .npmrc || echo "no .npmrc"
          # Determine tag from release (beta, alpha, etc.)
          TAG="latest"
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            TAG="next"
          fi

          echo "Publishing with tag: $TAG"
          npm publish --tag $TAG --access public --provenance
