name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn audit
      - run: yarn run prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          name: unit-tests
          flags: unit-tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn lint
      - run: yarn build
      - run: npx publint --pack npm
      - run: npx attw --pack . --profile node16
