name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit --prod
      - run: pnpm exec prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"
      - run: pnpm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          name: unit-tests
          flags: unit-tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: pnpm build
      - run: npx publint --pack npm
      - run: npx attw --pack . --profile node16
